{{- $suite := or .suite "bookworm" -}}
{{- $mirror := or .mirror "https://deb.debian.org/debian" -}}
{{- $hostname := or .hostname "citadel" -}}

architecture: "arm64"

actions:
  - action: debootstrap
    suite: {{ $suite }}
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    mirror: {{ $mirror }}

  - action: run
    description: Enable Bookworm security repo
    chroot: true
    command: |
      echo "" >> /etc/apt/sources.list
      echo "# Bookworm security repo" >> /etc/apt/sources.list
      echo "deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list

  - action: run
    description: Enable Bookworm updates repo
    chroot: true
    command: |
      echo "" >> /etc/apt/sources.list
      echo "# Bookworm updates repo" >> /etc/apt/sources.list
      echo "deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list

  - action: apt
    description: Install base packages
    update: true
    recommends: true
    packages:
      - sudo
      - openssh-server
      - vim
      - u-boot-menu
      - initramfs-tools
      - ca-certificates
      - man-db
      - console-setup
      - console-data
      - parted
      - bash-completion
      - xz-utils
      - zstd
      - ssh
      - wget
      - file
      - alsa-utils
      - dbus-broker
      - systemd-resolved
      - systemd-timesyncd
      - libpam-systemd
      - locales
      - manpages
      - pciutils
      - bzip2
      - lsof
      - traceroute
      - libnss-systemd
      - liblockfile-bin
      - e2fsprogs
      - ncurses-term
      - bluetooth
      - gawk
      - network-manager
      - curl

  - action: run
    description: Install standard packages
    chroot: true
    script: scripts/install-standard.sh

  # Can't use hostnamectl here because systemd isn't pid 1 in this case
  # or some garbage
  - action: run
    description: Set hostname
    chroot: true
    command: |
      echo "{{ $hostname }}" >/etc/hostname
      echo "127.0.0.1    localhost {{ $hostname }}" >/etc/hosts

  - action: overlay
    description: Copy custom systemd units
    source: overlays/systemd-units/
    destination: /usr/lib/systemd/system/

  - action: run
    description: Enable custom systemd units
    chroot: true
    command: |
      mkdir -p /etc/systemd/system/multi-user.target.wants
      ln -s /usr/lib/systemd/system/regen-openssh-keys.service /etc/systemd/system/multi-user.target.wants/regen-openssh-keys.service

  - action: overlay
    description: Copy resolved config fragments
    source: overlays/resolved/
    destination: /usr/lib/systemd/resolved.conf.d/

  - action: overlay
    description: Copy NetworkManager config fragments
    source: overlays/networkmanager/
    destination: /usr/lib/NetworkManager/conf.d/